# Generated by Django 4.2.7 on 2025-12-16 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message')),
                ('notification_type', models.CharField(choices=[('approval', 'Approval'), ('rejection', 'Rejection'), ('update', 'Status Update'), ('alert', 'Alert'), ('info', 'Information')], default='info', help_text='Type of notification', max_length=20)),
                ('related_entity', models.CharField(blank=True, help_text="Related entity (e.g., 'ClearanceRequest', 'ClearanceApproval')", max_length=100)),
                ('related_entity_id', models.CharField(blank=True, help_text='ID of related entity', max_length=100)),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was sent via email', null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
