# Generated by Django 4.2.7 on 2025-12-16 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payment'),
        ('clearances', '0002_initial'),
        ('approvals', '0002_initial'),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_e78525_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_entity',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_entity_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='approval',
            field=models.ForeignKey(blank=True, help_text='Related clearance approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='approvals.clearanceapproval'),
        ),
        migrations.AddField(
            model_name='notification',
            name='clearance',
            field=models.ForeignKey(blank=True, help_text='Related clearance request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='clearances.clearancerequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When notification email was sent', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Related payment record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_via_email',
            field=models.BooleanField(default=False, help_text='Whether notification email was sent'),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('clearance_submitted', 'Clearance Submitted'), ('clearance_approved', 'Clearance Approved'), ('clearance_rejected', 'Clearance Rejected'), ('approval_pending', 'Approval Pending'), ('payment_received', 'Payment Received'), ('payment_verified', 'Payment Verified'), ('payment_failed', 'Payment Failed'), ('general', 'General')], default='general', help_text='Type of notification', max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient'], name='notificatio_recipie_1dd18d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'),
        ),
    ]
