# Generated by Django 5.0.1 on 2026-01-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department_user_users_departm_5a2d9a_idx'),
    ]

    operations = [
    ]
