# Generated by Django 4.2.7 on 2025-12-16 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('login', 'Login'), ('logout', 'Logout'), ('other', 'Other')], help_text='Action type', max_length=20)),
                ('entity', models.CharField(help_text="Entity/Model name (e.g., 'ClearanceRequest', 'User')", max_length=100)),
                ('entity_id', models.CharField(help_text='ID of the entity', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Action description')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON object containing before/after values')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the requester', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
