# Generated by Django 4.2.7 on 2025-12-16 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, help_text='Date of approval/rejection', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable')),
                ('notes', models.TextField(blank=True, help_text='Additional notes from the approver')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clearance_approvals',
                'ordering': ['clearance_request', 'department__approval_order'],
            },
        ),
    ]
