# Generated by Django 4.2.7 on 2025-12-16 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('approvals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clearances', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceapproval',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who approved/rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clearanceapproval',
            name='clearance_request',
            field=models.ForeignKey(help_text='Clearance request being approved', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='clearances.clearancerequest'),
        ),
        migrations.AddField(
            model_name='clearanceapproval',
            name='department',
            field=models.ForeignKey(help_text='Department performing approval', on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='departments.department'),
        ),
        migrations.AddIndex(
            model_name='clearanceapproval',
            index=models.Index(fields=['clearance_request'], name='clearance_a_clearan_837151_idx'),
        ),
        migrations.AddIndex(
            model_name='clearanceapproval',
            index=models.Index(fields=['department'], name='clearance_a_departm_90f8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='clearanceapproval',
            index=models.Index(fields=['status'], name='clearance_a_status_22e181_idx'),
        ),
        migrations.AddIndex(
            model_name='clearanceapproval',
            index=models.Index(fields=['approval_date'], name='clearance_a_approva_2ad35b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clearanceapproval',
            unique_together={('clearance_request', 'department')},
        ),
    ]
