# Generated by Django 4.2.7 on 2025-12-16 19:51

import apps.approvals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceapproval',
            name='evidence_file',
            field=models.FileField(blank=True, help_text='Evidence document for clearance (max 5MB)', null=True, upload_to=apps.approvals.models.evidence_upload_path, validators=[apps.approvals.models.validate_evidence_file_size]),
        ),
    ]
