# Generated by Django 4.2.7 on 2025-12-16 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', help_text='Current clearance status', max_length=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True, help_text='Date clearance was submitted')),
                ('completion_date', models.DateTimeField(blank=True, help_text='Date clearance was completed/rejected', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason if clearance was rejected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clearance_requests',
                'ordering': ['-submission_date'],
            },
        ),
    ]
