# Generated by Django 4.2.7 on 2025-12-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('clearances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancerequest',
            name='student',
            field=models.ForeignKey(help_text='Student requesting clearance', on_delete=django.db.models.deletion.CASCADE, related_name='clearance_requests', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='clearancerequest',
            index=models.Index(fields=['student'], name='clearance_r_student_fb6d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='clearancerequest',
            index=models.Index(fields=['status'], name='clearance_r_status_e258ff_idx'),
        ),
        migrations.AddIndex(
            model_name='clearancerequest',
            index=models.Index(fields=['submission_date'], name='clearance_r_submiss_1c429b_idx'),
        ),
    ]
