# Generated by Django 4.2.7 on 2025-12-16 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tuition_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Outstanding tuition balance in KES', max_digits=10)),
                ('graduation_fee', models.DecimalField(decimal_places=2, default=5500.0, help_text='Graduation fee amount in KES', max_digits=10)),
                ('graduation_fee_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('verified', 'Verified')], default='pending', help_text='Graduation fee payment status', max_length=20)),
                ('mpesa_code', models.CharField(blank=True, help_text='M-PESA confirmation code for graduation fee', max_length=50)),
                ('mpesa_payment_date', models.DateTimeField(blank=True, help_text='Date of M-PESA payment', null=True)),
                ('last_verified_date', models.DateTimeField(blank=True, help_text='Last date when fees were verified', null=True)),
                ('verified_by', models.CharField(blank=True, help_text='Finance staff who verified the payment', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Finance notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_records',
            },
        ),
    ]
