# Generated by Django 4.2.7 on 2025-12-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='student',
            field=models.OneToOneField(help_text='Student finance information', on_delete=django.db.models.deletion.CASCADE, related_name='finance_record', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='financerecord',
            index=models.Index(fields=['student'], name='finance_rec_student_aae789_idx'),
        ),
        migrations.AddIndex(
            model_name='financerecord',
            index=models.Index(fields=['graduation_fee_status'], name='finance_rec_graduat_12f2e9_idx'),
        ),
    ]
