# Generated by Django 4.2.7 on 2025-12-16 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-PESA'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], default='mpesa', help_text='Payment method used', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction or receipt number', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Payer phone number (for M-PESA)', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, help_text='When payment was made', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether payment has been verified')),
                ('verification_date', models.DateTimeField(blank=True, help_text='When payment was verified', null=True)),
                ('notes', models.TextField(blank=True, help_text='Payment notes')),
                ('receipt', models.FileField(blank=True, help_text='Uploaded receipt', null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(help_text='Student payment record', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, help_text='User who verified the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student'], name='payments_student_5b85b3_idx'), models.Index(fields=['payment_method'], name='payments_payment_ee488d_idx'), models.Index(fields=['is_verified'], name='payments_is_veri_be791c_idx'), models.Index(fields=['created_at'], name='payments_created_e3a130_idx')],
            },
        ),
    ]
