# Generated by Django 4.2.7 on 2025-12-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fee_statement',
            field=models.FileField(blank=True, help_text='Uploaded fee statement document', null=True, upload_to='fee_statements/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='graduation_fee_amount',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Required graduation fee amount (KES 10,000)', max_digits=10),
        ),
    ]
