# Generated by Django 4.2.7 on 2025-12-16 19:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(help_text='School code (e.g., SCE, SBS)', max_length=20, unique=True)),
                ('dean_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academic_schools',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='academic_sc_code_ca80a8_idx'), models.Index(fields=['is_active'], name='academic_sc_is_acti_309a9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AcademicDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Department code (e.g., CS, ME)', max_length=20)),
                ('head_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.school')),
            ],
            options={
                'db_table': 'academic_departments',
                'ordering': ['school__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Course code (e.g., BSC-CS)', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.academicdepartment')),
            ],
            options={
                'db_table': 'academic_courses',
                'ordering': ['department__school__name', 'department__name', 'name'],
                'indexes': [models.Index(fields=['code'], name='academic_co_code_4be86c_idx'), models.Index(fields=['is_active'], name='academic_co_is_acti_694584_idx')],
                'unique_together': {('department', 'code')},
            },
        ),
        migrations.AddIndex(
            model_name='academicdepartment',
            index=models.Index(fields=['code'], name='academic_de_code_5e83fd_idx'),
        ),
        migrations.AddIndex(
            model_name='academicdepartment',
            index=models.Index(fields=['is_active'], name='academic_de_is_acti_0d87e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='academicdepartment',
            unique_together={('school', 'code')},
        ),
    ]
