# Generated by Django 4.2.7 on 2025-12-16 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(help_text='Student registration/admission number', max_length=50, unique=True)),
                ('faculty', models.CharField(help_text='Faculty/School name', max_length=255)),
                ('program', models.CharField(help_text='Program/Course name', max_length=255)),
                ('graduation_year', models.IntegerField(help_text='Expected graduation year')),
                ('eligibility_status', models.CharField(choices=[('eligible', 'Eligible'), ('ineligible', 'Ineligible'), ('pending', 'Pending Review')], default='pending', help_text='Academic eligibility status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
    ]
