# Generated by Django 4.2.7 on 2025-12-16 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(help_text='Link to user account', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['registration_number'], name='students_registr_f0f54d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['user'], name='students_user_id_b061ff_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['eligibility_status'], name='students_eligibi_032547_idx'),
        ),
    ]
