# Generated by Django 4.2.7 on 2025-12-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Academic Course/Program', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Academic Department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.academicdepartment'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Academic School/Faculty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.school'),
        ),
    ]
