# Generated by Django 4.2.7 on 2025-12-16 19:45

import apps.students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_course_student_department_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.IntegerField(blank=True, help_text='Year of admission (auto-extracted from registration number)', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(help_text='Student registration/admission number (format: SCHOOL/DEPT/NNNN/YYYY)', max_length=50, unique=True, validators=[apps.students.models.validate_registration_number]),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_year'], name='students_admissi_a3fee4_idx'),
        ),
    ]
