# Generated by Django 4.2.7 on 2025-12-16 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Department name', max_length=255)),
                ('code', models.CharField(help_text='Department code (e.g., FIN, LIB, MESS)', max_length=20, unique=True)),
                ('department_type', models.CharField(choices=[('finance', 'Finance Office'), ('faculty', 'Faculty/Academic'), ('library', 'Library'), ('mess', 'Mess/Cafeteria'), ('hostel', 'Hostel/Residence'), ('workshop', 'Workshop'), ('sports', 'Sports & Games'), ('other', 'Other')], help_text='Type of department', max_length=20)),
                ('head_email', models.EmailField(help_text='Department head email address', max_length=254)),
                ('description', models.TextField(blank=True, help_text='Department description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether department is active in the clearance process')),
                ('approval_order', models.IntegerField(default=0, help_text='Order in which this department should approve (0 = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['approval_order', 'name'],
                'indexes': [models.Index(fields=['code'], name='departments_code_9f933a_idx'), models.Index(fields=['department_type'], name='departments_departm_e45f0d_idx'), models.Index(fields=['is_active'], name='departments_is_acti_a777bd_idx')],
            },
        ),
    ]
