# Generated by Django 4.2.7 on 2025-12-16 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_student_admission_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GownIssuance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gown_number', models.CharField(help_text='Unique gown identifier/tag number', max_length=50, unique=True)),
                ('gown_size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], help_text='Gown size', max_length=5)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=2000.0, help_text='Deposit amount in KES (refundable on return)', max_digits=10)),
                ('deposit_paid', models.BooleanField(default=False, help_text='Whether deposit has been paid')),
                ('deposit_receipt', models.CharField(blank=True, help_text='Receipt number for deposit payment', max_length=100)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date gown was issued')),
                ('expected_return_date', models.DateField(help_text='Expected date for gown return')),
                ('actual_return_date', models.DateTimeField(blank=True, help_text='Actual date gown was returned', null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='issued', help_text='Current status of gown', max_length=20)),
                ('condition_notes', models.TextField(blank=True, help_text='Notes on gown condition (damage, stains, etc.)')),
                ('deposit_refunded', models.BooleanField(default=False, help_text='Whether deposit has been refunded')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount refunded (may be partial if damaged)', max_digits=10, null=True)),
                ('refund_date', models.DateTimeField(blank=True, help_text='Date deposit was refunded', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(help_text='Staff who issued the gown', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gowns_issued', to=settings.AUTH_USER_MODEL)),
                ('returned_to', models.ForeignKey(blank=True, help_text='Staff who received the returned gown', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gowns_received', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(help_text='Student issued the gown', on_delete=django.db.models.deletion.CASCADE, related_name='gown_issuance', to='students.student')),
            ],
            options={
                'db_table': 'gown_issuances',
                'ordering': ['-issued_date'],
                'indexes': [models.Index(fields=['student'], name='gown_issuan_student_c0a73f_idx'), models.Index(fields=['gown_number'], name='gown_issuan_gown_nu_12437c_idx'), models.Index(fields=['status'], name='gown_issuan_status_f27005_idx'), models.Index(fields=['issued_date'], name='gown_issuan_issued__6930e0_idx'), models.Index(fields=['expected_return_date'], name='gown_issuan_expecte_3169bd_idx')],
            },
        ),
    ]
